### ISSUE TITLE
run build error!

### ISSUE THREAD

**Issue by sixsir** [lo-th/Dedal.lab#2]
> rollup -c && java -jar utils/build/compiler/closure-compiler-v20160713.jar --warning_level=VERBOSE --jscomp_off=globalThis --jscomp_off=checkTypes --externs utils/build/externs.js --language_in=ECMASCRIPT5_STRICT --js build/ddls.js --js_output_file build/ddls.min.js

(!) You have passed an unrecognized option
Unknown input option: entry, indent, targets. Allowed options: acorn, acornInjectPlugins, cache, chunkGroupingSize, context, experimentalCacheExpiry, experimentalOptimizeChunks, experimentalTopLevelAwait, external, inlineDynamicImports, input, manualChunks, moduleContext, onwarn, perf, plugins, preserveModules, preserveSymlinks, shimMissingExports, treeshake, watch

 → stdout...
[!] Error: You must supply options.input to rollup
Error: You must supply options.input to rollup
    at Promise.all.then (F:\DedalPathFinding\node_modules\rollup\dist\rollup.js:16258:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ddls@1.0.1 build-closure: `rollup -c && java -jar utils/build/compiler/closure-compiler-v20160713.jar --warning_level=VERBOSE --jscomp_off=globalThis --jscomp_off=checkTypes --externs utils/build/externs.js --language_in=ECMASCRIPT5_STRICT --js build/ddls.js --js_output_file build/ddls.min.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ddls@1.0.1 build-closure script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-06-01T03_18_37_856Z-debug.log

How to fix it?

**Comment by lo-th** [comment]
is fix
